apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-db
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/argocd-2025/argocd-demo.git
    targetRevision: HEAD
    path: prod-mongo-db
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
